name: Make changelogs

on:
	push:
		branches: [master]
		types: [closed]

jobs:
	MakeCL:
		runs-on: ubuntu-latest
		if: github.repository == 'Citadel-Station-13/Citadel-Station-13-RP' && !contains(github.event.head_commit.message, '[ci skip]')
		steps:
			- name: Checkout
				uses: actions/checkout@v1
				with:
					fetch-depth: 25
			- name: Python setup
				uses: actions/setup-python@v1
				with:
					python-version: '3.x'
			- name: Install depends
				run: |
					python -m pip install --upgrade pip
					pip install ruamel.yaml PyGithub
			- name: Make CL
				env:
					#GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} Use this instead if you have unprotected branches
					GITHUB_TOKEN: ${{ secrets.CL_TOKEN }}
					GIT_EMAIL: "26690887+CitadelStationBot@users.noreply.github.com"
					GIT_NAME: "CitadelStationBot"
				run: python tools/changelog/generate_cl.py
